/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface CardsComponent {

    }
  }

  interface HTMLCardsComponentElement extends StencilComponents.CardsComponent, HTMLStencilElement {}

  var HTMLCardsComponentElement: {
    prototype: HTMLCardsComponentElement;
    new (): HTMLCardsComponentElement;
  };
  interface HTMLElementTagNameMap {
    'cards-component': HTMLCardsComponentElement;
  }
  interface ElementTagNameMap {
    'cards-component': HTMLCardsComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cards-component': JSXElements.CardsComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface CardsComponentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyCarousel {

    }
  }

  interface HTMLMyCarouselElement extends StencilComponents.MyCarousel, HTMLStencilElement {}

  var HTMLMyCarouselElement: {
    prototype: HTMLMyCarouselElement;
    new (): HTMLMyCarouselElement;
  };
  interface HTMLElementTagNameMap {
    'my-carousel': HTMLMyCarouselElement;
  }
  interface ElementTagNameMap {
    'my-carousel': HTMLMyCarouselElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-carousel': JSXElements.MyCarouselAttributes;
    }
  }
  namespace JSXElements {
    export interface MyCarouselAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;